src/urls.py
from django.contrib import admin
from rest_framework import routers
from django.urls import path,include
from django.contrib.auth.views import LoginView,LogoutView
from rest_framework.authtoken.views import obtain_auth_token  
from FastFoodEc.views import CustomObtainAuthToken,index_view,delivery_view,local_detail,register_user,agregar_pedido,profile,actualizar_cliente,carrito,agregar_producto,eliminar_producto,disminuir_producto,vaciar_carrito,mostrar_categoria
from FastFoodEc.api.api import LocalAPIView,CategoriaAPIView,ProductoAPIView,UserAPIView,ClienteAPIView,PedidoAPIView



router = routers.DefaultRouter()
router.register(r'Local', LocalAPIView)
router.register(r'Categoria', CategoriaAPIView)
router.register(r'Producto', ProductoAPIView)
router.register(r'User', UserAPIView)
router.register(r'Cliente', ClienteAPIView)
router.register(r'Pedido', PedidoAPIView)


urlpatterns = [
    path('',index_view,name = 'index'),
    path('api/', include(router.urls)),
    path('admin/', admin.site.urls),
    path('delivery/',delivery_view,name = 'delivery_view'),
    path('login/',LoginView.as_view(template_name = 'user/login.html'),name = 'login'),
    path('delivery/detail/<int:id_local>',local_detail,name = 'local_detail'),
    path('logout/',LogoutView.as_view(),name = 'logout'),
    path('register/',register_user,name = 'register'),
    path('pedido/',agregar_pedido,name = 'pedido'),
    path('account/<int:usuario_id>',profile,name = 'account'),
    path('update/<int:id_cliente>',actualizar_cliente,name = 'actualizarPerfil'),
    path('carrito/',carrito,name = 'carrito'),
    path('add/<int:idproducto>',profile,name = 'add_producto'),
    path('delivery/detail/<int:id_local>/categoria/<int:id_categoria>',mostrar_categoria,name = 'mostrar_categoria'),
    path('agregar/<int:producto_id>/', agregar_producto, name="agregar_producto"),
    path('eliminar/<int:producto_id>/', eliminar_producto, name="eliminar_producto"),
    path('restar/<int:producto_id>/', disminuir_producto, name="disminuir_producto"),
    path('vaciar/', vaciar_carrito, name="vaciar_carrito"),


]

FastFoodEc/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User

class Local(models.Model):
    nombre = models.CharField(max_length = 250, unique=True)
    imagen = models.CharField(max_length = 250)
    puntaje= models.FloatField(default=1, validators=[MaxValueValidator(5), MinValueValidator(1)])
    costoEnvio = models.FloatField()
    descripcion = models.CharField(max_length=150)
    tiempo_entrega = models.CharField(max_length=50)
    direccion = models.CharField(max_length=250)
       
    def __str__(self):
        return self.nombre

class Categoria(models.Model):
    nombre = models.CharField(max_length = 20)
    descripcion= models.CharField(max_length = 150)
    local = models.ForeignKey(Local, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.nombre} : {self.local.nombre}'


class Producto(models.Model):
    nombre = models.CharField(max_length = 100)
    imagen = models.CharField(max_length = 250)
    descripcion= models.CharField(max_length = 150)
    precio =models.FloatField()
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.nombre} : {self.categoria.nombre}'


class Persona(models.Model):
    nombres = models.CharField(max_length=150)
    apellidos = models.CharField(max_length=150)
    telefono = models.CharField(max_length=10)
    ciudad = models.CharField(max_length = 100)
    direccion = models.CharField(max_length=250)
    class Meta:
        abstract = True


class Cliente(Persona):
    imagen = models.CharField(max_length = 250)
    usuario = models.OneToOneField(User,on_delete= models.CASCADE)
    
    def __str__(self):
        return f'Cuenta de {self.usuario.username}'


class Pedido(models.Model):
    fecha_pedido = models.DateTimeField()
    total = models.FloatField()
    producto = models.ManyToManyField(Producto)
    direccion = models.CharField(max_length = 250)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    
    

FastFoodEc/views.py
from datetime import datetime
import datetime
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.authtoken.models import Token
from rest_framework.response import Response
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import  HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from FastFoodEc.Carrito import Carrito
from FastFoodEc.context_processor import total_carrito
from .models import Local,Categoria,Producto,Cliente,Pedido
from .forms import local_form,categoria_form,cliente_form,UserRegisterForm
from django.views.decorators.http import require_http_methods,require_safe

@require_safe
def index_view(request):
    return render(request,"index.html")

@login_required(login_url='login')
@require_safe
def admin_view(request):
    locales = Local.objects.all()
    categorias = Categoria.objects.all()
    productos = Producto.objects.all()
    
    context = {
        'locales':locales,
        'categorias':categorias,
        'productos':productos
    }

    return render(request,"./admin/admin.html",context)

@login_required(login_url='login')
@require_safe
def local_view(request):
    locales = Local.objects.all()

    if request.method == "POST":
        form_categoria = categoria_form(request.POST)
        if form_categoria.is_valid():
            Categoria.objects.create(**form_categoria.cleaned_data)
    context = {
        'locales':locales,
    }

    return render(request,"./local/local.html",context)
    
@login_required(login_url='login')
@require_http_methods(["GET", "POST"])
def agregar_local_view(request):
    form = local_form
   
    context ={
        'form':form,
    }

    return render(request,"local/agregar.html",context)

@login_required(login_url='login')
@require_http_methods(["GET", "POST"])
def agregar_local_categorias(request):

    form_categoria = categoria_form
    if request.method == "POST":
        form = local_form(request.POST)
        if form.is_valid():
            Local.objects.create(**form.cleaned_data)
    
    context ={
        'formCategoria':form_categoria
    }

    return render(request,"local/agregar_categoria.html",context)


@login_required(login_url='login')
@require_safe
def view_local(request,id):
    local = Local.objects.get(id=id)
    categorias =Categoria.objects.get(local_id=id)
    context={
        'local':local,
        'categorias':categorias
    }
    return render(request,"local/view.html",context)

@require_http_methods(["POST" ,"GET"])
def register_user(request):
    form_cliente = cliente_form
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            data = form.save()
           
            data_user ={
                'google_maps_api_key': settings.GOOGLE_MAPS_API_KEY,
                "idUser":data.id,
                "formC":form_cliente
            }
            return render(request,'user/register-complete.html',data_user)

    else:
        form = UserRegisterForm()

    if request.method == 'POST':
        form_cliente = cliente_form(request.POST)
        if form_cliente.is_valid():
            cliente = Cliente()
            user = User.objects.get(id =request.POST['usuario_id'])
            cliente.imagen= form_cliente.cleaned_data['imagen']
            cliente.nombres = form_cliente.cleaned_data['nombres']
            cliente.apellidos= form_cliente.cleaned_data['apellidos']
            cliente.telefono= form_cliente.cleaned_data['telefono']
            cliente.ciudad = form_cliente.cleaned_data['ciudad']
            cliente.direccion = form_cliente.cleaned_data['direccion']
            cliente.usuario = user
            cliente.save()
            return HttpResponseRedirect(reverse('login'))


    context={
        'form':form
    }

    return render(request,"user/register.html",context)


@login_required(login_url='login')
@require_safe
def delivery_view(request):
    user = request.user
    locales = Local.objects.all()
    cliente = Cliente.objects.get(usuario_id=user.id)
    context = {
        'locales':locales,
        'cliente':cliente
      
    }
    
    return render(request,"delivery/delivery.html",context)

@login_required(login_url='login')
@require_safe
def profile(request,usuario_id):
    form_cliente = cliente_form
    user = request.user
    cliente = Cliente.objects.get(usuario_id=usuario_id)
    pedidos =  Pedido.objects.order_by('-fecha_pedido').filter(user_id=user.id)

    context = {
        'cliente':cliente,
        'pedidos':pedidos,
        'form':form_cliente,
    }
    
    return render(request,"delivery/profile.html",context)

@login_required(login_url='login')
@require_safe
def local_detail(request,id_local):
    local = Local.objects.get(id=id_local)

    categorias = Categoria.objects.order_by('nombre').filter(local_id=id_local)
    ids_categorias = Categoria.objects.filter(local_id=id_local).values_list('id', flat=True)
    productos =  Producto.objects.order_by('nombre').filter(categoria_id__in=ids_categorias)
    user = request.user
    cliente = Cliente.objects.get(usuario_id=user.id)

    context={
        "local":local,
        "categorias":categorias,
        "productos":productos,
        'cliente':cliente
    }

    return render(request,"delivery/local_detail.html",context)

@login_required(login_url='login')
@require_safe
def mostrar_categoria(request,id_local,id_categoria):
    local = Local.objects.get(id=id_local)
    categoria = Categoria.objects.get(id=id_categoria)
    productos =  Producto.objects.order_by('nombre').filter(categoria_id=id_categoria)
    categorias = Categoria.objects.order_by('nombre').filter(local_id=id_local)
    user = request.user
    cliente = Cliente.objects.get(usuario_id=user.id)

    context = {
        "productosC":productos,
        'cliente':cliente,
        "local":local,
        "categoriaN":categoria,
        "categorias":categorias
    }

    return render(request,"delivery/categoria.html",context)

@login_required(login_url='login')
@require_safe
def carrito(request):
    user = request.user
    cliente = Cliente.objects.get(usuario_id=user.id)
    context = {
        'cliente':cliente
    }
    
    return render(request,"delivery/carrito.html",context)

@login_required(login_url='login')
@require_http_methods(["GET"])
def agregar_pedido(request):
    productos = []

    user = request.user
    usuario = User.objects.get(id=user.id)
    cliente = Cliente.objects.get(usuario_id=user.id)
    fecha = datetime.datetime.now()
    fecha_formato = fecha.strftime("%Y-%m-%d %H:%M:%S")

    total = total_carrito(request)
    print(cliente)
    print(total['total_carrito'])
    carrito = Carrito(request) 

    pedido = Pedido.objects.create(fecha_pedido = fecha_formato, total = total['total_carrito'], direccion = cliente.direccion, user = usuario)
    
    for key, value in carrito.carrito_session.items():  # Aquí se hace el cambio
        producto = Producto.objects.get(id=value["producto_id"])
        productos.append(producto)
        print(f'{value["producto_id"]} : {value["nombre"]}')

    pedido.producto.set(productos)
    
    carrito.vaciar_carrito()
    return redirect('delivery_view')


@login_required(login_url='login')
@require_http_methods(["POST", "GET"])
def agregar_producto(request, producto_id):

    id_categoria = Producto.objects.filter(id=producto_id).values_list('categoria_id', flat=True)
    local_id = Categoria.objects.filter(id=id_categoria[0]).values_list('local_id', flat=True)
    carrito = Carrito(request)
    producto = Producto.objects.get(id=producto_id)
    carrito.agregar_producto(producto)

    return redirect("local_detail",id_local=local_id[0])


@login_required(login_url='login')
@require_http_methods(["POST"])
def eliminar_producto(request, producto_id):
    id_categoria = Producto.objects.filter(id=producto_id).values_list('categoria_id', flat=True)
    id_local = Categoria.objects.filter(id=id_categoria[0]).values_list('local_id', flat=True)
    carrito = Carrito(request)
    producto = Producto.objects.get(id=producto_id)
    carrito.eliminar_producto(producto)
    
    return redirect("local_detail",id=id_local[0])

@login_required(login_url='login')
@require_http_methods(["POST","GET"])
def disminuir_producto(request, producto_id):
    id_categoria = Producto.objects.filter(id=producto_id).values_list('categoria_id', flat=True)
    id_local = Categoria.objects.filter(id=id_categoria[0]).values_list('local_id', flat=True)
    carrito = Carrito(request)
    producto = Producto.objects.get(id=producto_id)
    carrito.disminuir_producto(producto)
    return redirect("local_detail",id_local=id_local[0])

@login_required(login_url='login')

@require_http_methods(["POST","GET"])
def vaciar_carrito(request):
    carrito = Carrito(request)
    carrito.vaciar_carrito()
    return redirect("delivery_view",)

@login_required(login_url='login')
@require_http_methods(["POST"])
def actualizar_cliente(request,id_cliente):
    user = request.user
    cliente = Cliente.objects.get(id=id_cliente)
    print(cliente.nombres)
    cliente.imagen= request.POST['imagen']
    cliente.nombres = request.POST['nombres']
    cliente.apellidos= request.POST['apellidos']
    cliente.telefono= request.POST['telefono']
    cliente.ciudad = request.POST['ciudad']
    cliente.direccion = request.POST['direccion']
    cliente.save()
    
    return redirect("account",usuario_id=user.id)

class CustomObtainAuthToken(ObtainAuthToken):
    @require_http_methods(["POST"])
    def post(self, request, *args, **kwargs):

FastFoodEc/templates/delivery/carrito.html
{%extends 'delivery/nav_bar_delivery.html' %}

{%block content%} 
<div class="content-carrito">
  <div class="modal fade" id="delete-address-modal" tabindex="-1" role="dialog" aria-labelledby="delete-address" aria-hidden="true">
    <div class="modal-dialog modal-sm modal-dialog-centered" role="document">
    <div class="modal-content">
    <div class="modal-header">
    <h5 class="modal-title" id="delete-address">Pagar</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
    </div>
    <div class="modal-body">
      <div class="pago">
        <div class="pago-titulo">
          <h3 class="titulo-pago">Añadir Pago</h3>
          <img class="payment-cardimg"
          src="//my-assets.netlify.com/codepen/dailyui-002/img_cards.svg" alt="carts">
        </div>
        <div class="datos-pago">
          <label for="" class="label-pago"> Nombre del titular de la tarjeta</label>
          <input type="text" class="input-pago" placeholder="Nombre del titular de la tarjeta">
          <label for="" class="label-pago"> Número de la tarjeta</label>
          <input type="text" class="input-pago" placeholder="1234 - 5678 - 9876 - 5432" >
        </div>

        <div class="datos-fecha">

         <div class="datos-fecha-pago">
          <label for="" class="label-pago">Año de Expiración</label>
          <input type="text"  class="input-tarjeta" placeholder="MM/YY">
         </div>

         <div class="datos-cvc">
          <label for="" class="label-pago"> CVC </label>
          <input type="text"  class="input-tarjeta"placeholder="XXX">
         </div>
          

        </div>



      </div>
      
    
    </div>
    <div class="modal-footer">
    <button type="button" class="btn d-flex w-50 text-center justify-content-center btn-outline-primary" data-dismiss="modal">CANCELAR
    </button><button type="button" onclick="pago()" class="btn d-flex w-50 text-center justify-content-center btn-primary"> <a href="{% url 'pedido' %}"> PAGAR {{total_carrito}}</a></button>
    </div>
    </div>
    </div>
    </div>
    <div class="content-carrito-productos" role="alert">
        <table class="tabla ">
          <caption> Tabla Carrito</caption>
          <thead>
            <tr>
              <th scope="row" colspan="3" class="text-center"> <i class="fa-solid fa-cart-shopping"></i> CARRITO</th>
            </tr>
            <tr>
              <th scope="col">NOMBRE</th>
              <th scope="col">PRECIO</th>
              <th scope="col">CANTIDAD</th>
            </tr>
          </thead>
          <tbody>
          {% if request.session.carrito.items %}
          {% for key, value in request.session.carrito.items %}
            <tr>
              <td><img src="{{value.imagen}}"  class="img-cart" alt="" width="50" height="50"> {{value.nombre}}</td>
              <td>$ {{value.total}}</td>
              <td> <a href="{% url 'agregar_producto' value.producto_id %}" ><button class="btn-cart"> + </button></a>
                x {{value.cantidad}}
                <a href="{% url 'disminuir_producto' value.producto_id %}" ><button class="btn-cart"> - </button></a>
              </td>
            </tr>
          {% endfor %}
          {% else %}
          <tr>
              <td colspan="3">
                  <div class="alert alert-danger text-center"> Sin Productos </div>
              </td>
          </tr>
          {% endif %}
            <tr>
              <th scope="row">Total:</th>
              <td > $ {{total_carrito}}</td>
            </tr>
          </tbody>
        </table>
        <hr>
        {% if request.session.carrito.items %}
        <div class="row text-center">
            <div class="div-btn-quitar"><a href="{% url 'vaciar_carrito' %}"><button  class="btn-quitar " > Quitar Todo</button></a></div>
            <div class="div-btn-pagar"><a class="text-danger" data-toggle="modal" data-target="#delete-address-modal" href="#" href="" ><button class="btn-pagar " >Pagar $ {{total_carrito}}</button></a></div>
            
        </div>
        {% endif %}
        </div>

    
</div>
{%endblock%}

FastFoodEc/templates/delivery/delivery.html

{%extends 'delivery/nav_bar_delivery.html' %}

{%block content %} 

<section class="section">
    
<div class="content-section">

    <div class="content-section-banner">
        <div class="banner">
            <h1>ENCUENTRA LOS MEJORES</h1>
            <h1>SABORES DE <span>ECUADOR </span></h1>
            <h5>DESCUBRE LO QUE TENEMOS PREPARADO PARA TI</h5>
        </div>
        <div class="content-section-img">
            
            <img src="https://dam.cocinafacil.com.mx/wp-content/uploads/2020/04/comida-china-tipica.jpg" width="400px" height="200px" alt="img1">
        </div>
    </div>
</div>



</section>


<section class="section-resturantes">
<div class="section-resturantes-container">
   <div class="section-resturantes-container-tittle">
            <h1 class="tittle-section-restaurant"> <b>Locales Disponibles </b> </h1>
            <h5> Escoge los mejores lugares para encontrar tu comida preferida.</h5>
   </div>

   <div class="container-restaurant">
        <div class="item-list-restaurant ">
                {% for local in locales %}
            <div class="list-card">
                    <div class="list-card-image">     
                        <a href="detail/{{local.id}}">
                        <img src="{{local.imagen}}" class="item-img" alt="local">
                        </a>
                    </div>
                        <div class="p-3 ">
                            <div class="list-card-body" >
                                        <h6 class="mb-1"><a href="detail.html" class="text-black">{{local.nombre}}</a></h6>
                                        <p class="text-gray mb-3">{{local.descripcion}}</p>            
                                            <div class="stars-outer" >
                                                <p id="puntaje" class="puntaje">{{local.puntaje}}</p>
                                                <div class="local_{{local.id}} stars-inner"></div>
                                            </div>
                                        {% if local.costoEnvio > 0 %}
                                        <p class="time"><span class="bg-light "><i class="fa-solid fa-clock"></i> {{local.tiempo_entrega}} min</span> <span class="float-right"><i class="fa-solid fa-truck-moving"></i> Envío ${{local.costoEnvio}} </span></p>
                                        {% else %}
                                        <p class="time"><span class="bg-light "><i class="fa-solid fa-clock"></i> {{local.tiempo_entrega}} min</span> <span class="float-right"><i class="fa-solid fa-truck-moving"></i> Envío Gratis </span></p>
                                        {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>   
</div>

</section>

{%endblock%}


FastFoodEc/templates/delivery/profile.html
{%extends 'delivery/nav_bar_delivery.html' %}
{% load static %}

<link rel="stylesheet" href="{% static 'polls/osahan' %}">
{%block content%} 
<div class="modal fade" id="delete-address-modal" tabindex="-1" role="dialog" aria-labelledby="delete-address" aria-hidden="true">
    <div class="modal-dialog modal-sm modal-dialog-centered" role="document">
    <div class="modal-content">
    <div class="modal-header">
    <h5 class="modal-title" id="delete-address">Editar Perfil</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
    </div>
    <div class="modal-body">
    <div class="edit-profile" id="edit-profile" >
        <form action="/update/{{cliente.id}}" method="post"  > {%csrf_token%} 
            <img class="img-account" id="img-profile-account" alt="profile" src="https://clubsuizomadrid.org/assets/images/juntadirectiva/user-gray.png"  >
                    <p>
                    <input class="input-form-c" id="url-img-profile" name="imagen"  placeholder="Foto de Perfil" required="" type="text" value="{{cliente.imagen}}" onchange="cargarImagen()">
                    </p>
                    <p>
                    <input class="input-form-c" id="id_nombres" name="nombres" placeholder="Nombres" required="" type="text" value="{{cliente.nombres}}">
                    </p>
                    <p>
                    <input class="input-form-c" id="id_apellidos" name="apellidos" placeholder="Apellidos" required="" type="text" value="{{cliente.apellidos}}">
                    </p>
                    <p>
                    <input class="input-form-c" id="id_telefono" name="telefono" placeholder="Telefono" required="" type="text" value="{{cliente.telefono}}">
                    </p>
                    <p>
                    <input class="input-form-c" id="id_ciudad" name="ciudad" placeholder="Ciudad" required="" type="text" value="{{cliente.ciudad}}">
                    </p>
                    <p>
                    <input class="input-form-c" id="id_direccion" name="direccion" placeholder="Dirección" required="" type="text" value="{{cliente.direccion}}">
                    </p>
                    <div class="modal-footer">
                    <button class="btn d-flex w-50 text-center justify-content-center btn-outline-primary" data-dismiss="modal" type="button">CANCELAR
                    </button><button class="btn d-flex w-50 text-center justify-content-center btn-primary" type="submit">  EDITAR</button>
                    </div>
        


    </form>
        
    </div>

    </div>

    </div>
    </div>
    </div>

<div class="modal fade" id="edit-profile-modal" tabindex="-1" role="dialog" aria-labelledby="edit-profile" aria-hidden="true">
    <div class="modal-dialog modal-sm modal-dialog-centered" role="document">
    <div class="modal-content">
    <div class="modal-body">
    </div>
    </div>
    </div>
    </div>
    

    <section class="section pt-4 pb-4 osahan-account-page">
    <div class="container">
    <div class="row">
    <div class="col-md-3">
    <div class="osahan-account-page-left shadow-sm bg-white h-100">
    <div class="border-bottom p-4">
    <div class="osahan-user text-center">
    <div class="osahan-user-media">
    <img alt="imgclient" class="mb-3 rounded-pill shadow-sm mt-1 img-account" src="{{cliente.imagen}}" >
    <div class="osahan-user-media-body">
    <h6 class="mb-2">{{cliente.nombres}}</h6>
    <p class="mb-1">+593 {{cliente.telefono}}</p>
    <p><a href="" class="__cf_email__" >{{user.email}}</a></p>
    <p class="mb-0 text-black font-weight-bold"><a class="text-primary mr-3" data-toggle="modal" data-target="#delete-address-modal" href="#"> EDITAR PERFIL</a></p>
    </div>
    </div>
    </div>
    </div>
    <ul class="nav nav-tabs flex-column border-0 pt-4 pl-4 pb-4" id="myTab" role="tablist">
    <li class="nav-item">
    <a class="nav-link active" id="orders-tab" data-toggle="tab" href="#orders" role="tab" aria-controls="orders" aria-selected="true"><i class="fa-solid fa-plate-wheat"></i>Pedidos</a>
    </li>
    <li class="nav-item">
    <a class="nav-link" id="addresses-tab" data-toggle="tab" href="#addresses" role="tab" aria-controls="addresses" aria-selected="false"><i class="fa-solid fa-location-dot"></i>Direcciones</a>
    </li>
    </ul>
    </div>
    </div>
    <div class="col-md-9">
    <div class="osahan-account-page-right shadow-sm bg-white p-4 h-100">
    <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="orders" role="tabpanel" aria-labelledby="orders-tab">
    <h4 class="font-weight-bold mt-0 mb-4">Pedidos</h4>

    {{producto.nombre}}
    
    {% if pedidos|length > 0 %}
    {% for pedido in pedidos %}
    <div class="bg-white card mb-4 order-list shadow-sm">

        <div class="gold-members p-4">
        <a href="#">
        <div class="media">
        <img class="mr-4" src="{% static 'img/logo.png' %}" width="80" height="50" alt="logo">
        <div class="media-body">
        <span class="float-right text-info">{{pedido.fecha_pedido}} <i class="fa-solid fa-circle-check"></i></span>
        <h6 class="mb-2">
        <a href="" class="text-black">Fast Food Ecuador
        </a></h6>
        <p class="text-gray mb-1"><i class="fa-solid fa-location-arrow"></i>{{pedido.direccion}}
        </p>
        <p class="text-gray mb-3"><i class="fa-solid fa-clipboard-list"></i>ORDEN #{{pedido.id}} <i class="fa-solid fa-clock"></i>{{pedido.fecha_pedido}}</p>
        <p class="text-dark">  {% for p in pedido.producto.all %} {{p.nombre}} x {{pedido.producto.count}}, {% endfor %}
        </p>
        <hr>

        <p class="mb-0 text-black text-primary pt-2"><span class="text-black font-weight-bold"> Total:</span> $ {{pedido.total}}
        </p>
        </div>
        </div>
        </a>
        </div>
    </div>
        {% endfor %}

    {% else %}
       
        <img src="https://s3-vultec-pe.s3-us-west-2.amazonaws.com/media/uploads/froala_editor/images/carritovacio.png" width="400" height="400" class="img-nopedido" alt="no-pedido">
        <h5 class="no-pedido"> Vaya al parecer aún has realizado ningún pedido</h5>
    {% endif %}

    
    

    </div>
    <div class="tab-pane fade" id="addresses" role="tabpanel" aria-labelledby="addresses-tab">
    <h4 class="font-weight-bold mt-0 mb-4">Direcciones</h4>
    <div class="direciones">
        <div class="col-md-6">
            <div class="bg-white card addresses-item shadow-sm">
                <div class="gold-members p-4">
                    <div class="media">
                    <div class="mr-3"></div>
                    <div class="media-body">
                    <h6 class="mb-1"><i class="fa-solid fa-location-dot"></i>Casa</h6>
                    <p>{{cliente.direccion}}
                    </p>
                    </div>
                    </div>
                </div>
            </div>
        </div>
        
    </div>


    </div>
    </div>
    </div>
    </div>
    
    </div>
    
    </div>
    
    <script src="{% static 'javascript/script.js' %}"></script>
    {%endblock%}
    </section>
    </div>